In [195]:
import pandas as pd

df_2023 = pd.read_csv("data/raw/halfmarathon_wroclaw_2023__final.csv")
df_2024 = pd.read_csv("data/raw/halfmarathon_wroclaw_2024__final.csv")

print("2023:", df_2023.shape)
print("2024:", df_2024.shape)

2023: (8950, 1)
2024: (13007, 1)

In [196]:
df_2023

     Miejsce;Numer startowy;Imię;Nazwisko;Miasto;Kraj;Drużyna;Płeć;Płeć Miejsce;Kategoria wiekowa;Kategoria wiekowa Miejsce;Rocznik;5 km Czas;5 km Miejsce Open;5 km Tempo;10 km Czas;10 km Miejsce Open;10 km Tempo;15 km Czas;15 km Miejsce Open;15 km Tempo;20 km Czas;20 km Miejsce Open;20 km Tempo;Tempo Stabilność;Czas;Tempo
0     1.0;1787;TOMASZ;GRYCKO;;POL;UKS BLIZA WŁADYSŁA...
1     2.0;3;ARKADIUSZ;GARDZIELEWSKI;WROCŁAW;POL;ARKA...
2     3.0;3832;KRZYSZTOF;HADAS;POZNAŃ;POL;;M;3;M20;1...
3     4.0;416;DAMIAN;DYDUCH;KĘPNO;POL;AZS POLITECHNI...
4     5.0;8476;KAMIL;MAŃKOWSKI;MIRKÓW;POL;PARKRUN WR...
...                                                 ...
8945  ;8901;KAROL;ŻUKOWSKI;;;Ovb Polska;M;;M30;;1990...
8946  ;659;KORNELIA;ŻUKROWSKA;;;;K;;K30;;1988.0;;;;;...
8947  ;6402;MAGDALENA;ŻÓRAŃSKA;;;Iławskie Świry Bieg...
8948  ;2771;KATARZYNA;ĆWIĄKALSKA;;;;K;;K40;;1982.0;;...
8949  ;2773;JULIUSZ;ĆWIĄKALSKI;;;;M;;M40;;1983.0;;;;...

[8950 rows x 1 columns]

In [197]:
df_2023.columns

Index(['Miejsce;Numer startowy;Imię;Nazwisko;Miasto;Kraj;Drużyna;Płeć;Płeć Miejsce;Kategoria wiekowa;Kategoria wiekowa Miejsce;Rocznik;5 km Czas;5 km Miejsce Open;5 km Tempo;10 km Czas;10 km Miejsce Open;10 km Tempo;15 km Czas;15 km Miejsce Open;15 km Tempo;20 km Czas;20 km Miejsce Open;20 km Tempo;Tempo Stabilność;Czas;Tempo'], dtype='object')

In [198]:
df_2023.shape

(8950, 1)

In [199]:
import pandas as pd

df_2023 = pd.read_csv(
    "data/raw/halfmarathon_wroclaw_2023__final.csv",
    sep=";"
)

df_2024 = pd.read_csv(
    "data/raw/halfmarathon_wroclaw_2024__final.csv",
    sep=";"
)

print("2023:", df_2023.shape)
print("2024:", df_2024.shape)

2023: (8950, 27)
2024: (13007, 27)

In [200]:
df_2023.columns.tolist()

['Miejsce',
 'Numer startowy',
 'Imię',
 'Nazwisko',
 'Miasto',
 'Kraj',
 'Drużyna',
 'Płeć',
 'Płeć Miejsce',
 'Kategoria wiekowa',
 'Kategoria wiekowa Miejsce',
 'Rocznik',
 '5 km Czas',
 '5 km Miejsce Open',
 '5 km Tempo',
 '10 km Czas',
 '10 km Miejsce Open',
 '10 km Tempo',
 '15 km Czas',
 '15 km Miejsce Open',
 '15 km Tempo',
 '20 km Czas',
 '20 km Miejsce Open',
 '20 km Tempo',
 'Tempo Stabilność',
 'Czas',
 'Tempo']

In [201]:
df_2023

,Miejsce,Numer startowy,Imię,Nazwisko,Miasto,Kraj,Drużyna,Płeć,Płeć Miejsce,Kategoria wiekowa,...,10 km Tempo,15 km Czas,15 km Miejsce Open,15 km Tempo,20 km Czas,20 km Miejsce Open,20 km Tempo,Tempo Stabilność,Czas,Tempo
0,1.0,1787,TOMASZ,GRYCKO,NaN,POL,UKS BLIZA WŁADYSŁAWOWO,M,1.0,M30,...,2.926667,00:44:47,1.0,3.106667,01:01:43,1.0,3.386667,0.031400,01:04:59,3.080509
1,2.0,3,ARKADIUSZ,GARDZIELEWSKI,WROCŁAW,POL,ARKADIUSZGARDZIELEWSKI.PL,M,2.0,M30,...,2.983333,00:45:26,2.0,3.143333,01:03:08,2.0,3.540000,0.038000,01:06:23,3.146875
2,3.0,3832,KRZYSZTOF,HADAS,POZNAŃ,POL,NaN,M,3.0,M20,...,3.123333,00:47:34,3.0,3.236667,01:05:09,3.0,3.516667,0.024067,01:08:24,3.242475
3,4.0,416,DAMIAN,DYDUCH,KĘPNO,POL,AZS POLITECHNIKA OPOLSKA,M,4.0,M30,...,3.196667,00:48:49,5.0,3.330000,01:06:54,4.0,3.616667,0.025467,01:10:16,3.330963
4,5.0,8476,KAMIL,MAŃKOWSKI,MIRKÓW,POL,PARKRUN WROCŁAW,M,5.0,M20,...,3.276667,00:49:31,7.0,3.386667,01:07:27,5.0,3.586667,0.023000,01:10:27,3.339654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,NaN,8901,KAROL,ŻUKOWSKI,NaN,NaN,Ovb Polska,M,NaN,M30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DNF,NaN
8946,NaN,659,KORNELIA,ŻUKROWSKA,NaN,NaN,NaN,K,NaN,K30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DNS,NaN
8947,NaN,6402,MAGDALENA,ŻÓRAŃSKA,NaN,NaN,Iławskie Świry Biegowe,K,NaN,K40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DNS,NaN
8948,NaN,2771,KATARZYNA,ĆWIĄKALSKA,NaN,NaN,NaN,K,NaN,K40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DNS,NaN
8949,NaN,2773,JULIUSZ,ĆWIĄKALSKI,NaN,NaN,NaN,M,NaN,M40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DNS,NaN

In [202]:
df_2023.shape

(8950, 27)

In [203]:
df_2023.columns.tolist()

['Miejsce',
 'Numer startowy',
 'Imię',
 'Nazwisko',
 'Miasto',
 'Kraj',
 'Drużyna',
 'Płeć',
 'Płeć Miejsce',
 'Kategoria wiekowa',
 'Kategoria wiekowa Miejsce',
 'Rocznik',
 '5 km Czas',
 '5 km Miejsce Open',
 '5 km Tempo',
 '10 km Czas',
 '10 km Miejsce Open',
 '10 km Tempo',
 '15 km Czas',
 '15 km Miejsce Open',
 '15 km Tempo',
 '20 km Czas',
 '20 km Miejsce Open',
 '20 km Tempo',
 'Tempo Stabilność',
 'Czas',
 'Tempo']

In [204]:
df = pd.concat([df_2023, df_2024], ignore_index=True)

print(df.shape)

(21957, 27)

In [205]:
df[['Płeć', 'Rocznik', '5 km Czas', 'Czas']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21957 entries, 0 to 21956
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Płeć       21946 non-null  object
 1   Rocznik    21472 non-null  float64
 2   5 km Czas  18411 non-null  object
 3   Czas       19902 non-null  object
dtypes: float64(1), object(3)
memory usage: 686.3+ KB

In [206]:
df[['Płeć', 'Rocznik', '5 km Czas', 'Czas']].isna().sum()

Płeć           11
Rocznik       485
5 km Czas    3546
Czas         2055
dtype: int64

In [207]:
df.shape

(21957, 27)

In [208]:
df_model = df[
    ['Płeć', 'Rocznik', '5 km Czas', 'Czas']
].copy()

df_model = df_model.dropna()

print(df_model.shape)

(17927, 4)

In [209]:
df_model.isna().sum()

Płeć         0
Rocznik      0
5 km Czas    0
Czas         0
dtype: int64

In [210]:
df_model[['5 km Czas', 'Czas']]

      5 km Czas      Czas
0      00:14:37  01:04:59
1      00:14:48  01:06:23
2      00:15:46  01:08:24
3      00:16:11  01:10:16
4      00:16:12  01:10:27
...         ...       ...
19244  00:39:56  03:17:46
19245  00:43:30  03:19:47
19246  00:42:06  03:21:08
19247  00:49:20  03:22:18
19248  00:46:48  03:28:32

[17927 rows x 2 columns]

In [211]:
df_model["time_5km_sec"] = (
    pd.to_timedelta(df_model["5 km Czas"])
    .dt.total_seconds()
)

df_model["time_half_sec"] = (
    pd.to_timedelta(df_model["Czas"])
    .dt.total_seconds()
)

df_model[
    ["5 km Czas", "time_5km_sec",
     "Czas", "time_half_sec"]
].head()

  5 km Czas  time_5km_sec      Czas  time_half_sec
0  00:14:37         877.0  01:04:59         3899.0
1  00:14:48         888.0  01:06:23         3983.0
2  00:15:46         946.0  01:08:24         4104.0
3  00:16:11         971.0  01:10:16         4216.0
4  00:16:12         972.0  01:10:27         4227.0

In [212]:
df_model = df_model.rename(columns={
    "5 km Czas": "time_5km",
    "Czas": "time_half",
    "Rocznik": "year_birth",
    "Płeć": "gender"
})

In [213]:
CURRENT_YEAR = 2024

df_model["age"] = CURRENT_YEAR - df_model["year_birth"]

In [214]:
df_model[["year_birth", "age"]]

       year_birth   age
0          1992.0  32.0
1          1986.0  38.0
2          1996.0  28.0
3          1988.0  36.0
4          1995.0  29.0
...           ...   ...
19244      1977.0  47.0
19245      1948.0  76.0
19246      1978.0  46.0
19247      1955.0  69.0
19248      1981.0  43.0

[17927 rows x 2 columns]

In [215]:
df_model[
    ["gender", "age", "time_5km_sec", "time_half_sec"]
]

      gender   age  time_5km_sec  time_half_sec
0          M  32.0         877.0         3899.0
1          M  38.0         888.0         3983.0
2          M  28.0         946.0         4104.0
3          M  36.0         971.0         4216.0
4          M  29.0         972.0         4227.0
...      ...   ...           ...            ...
19244      K  47.0        2396.0        11866.0
19245      K  76.0        2610.0        11987.0
19246      K  46.0        2526.0        12068.0
19247      K  69.0        2960.0        12138.0
19248      K  43.0        2808.0        12512.0

[17927 rows x 4 columns]

In [216]:
df_model[
    ["age", "time_5km_sec", "time_half_sec"]
].describe()

                age  time_5km_sec  time_half_sec
count  17927.000000  17927.000000   17927.000000
mean      41.615887   1672.398896    7392.332627
std       63.679861    246.903126    1212.071213
min       18.000000      0.000000    3843.000000
25%       32.000000   1501.000000    6544.000000
50%       39.000000   1660.000000    7240.000000
75%       46.000000   1833.000000    8128.000000
max     2024.000000   3825.000000   12512.000000

In [217]:
df_model["gender"].value_counts()

M    12760
K     5167
Name: gender, dtype: int64

In [218]:
X = df_model[
    ["gender", "age", "time_5km_sec"]
]

y = df_model["time_half_sec"]

In [219]:
df_model[
    ["age", "time_5km_sec", "time_half_sec"]
].describe()

                age  time_5km_sec  time_half_sec
count  17927.000000  17927.000000   17927.000000
mean      41.615887   1672.398896    7392.332627
std       63.679861    246.903126    1212.071213
min       18.000000      0.000000    3843.000000
25%       32.000000   1501.000000    6544.000000
50%       39.000000   1660.000000    7240.000000
75%       46.000000   1833.000000    8128.000000
max     2024.000000   3825.000000   12512.000000

In [220]:
df_model["gender"].value_counts()

M    12760
K     5167
Name: gender, dtype: int64

In [221]:
df_model = df_model[
    (df_model["age"] >= 18) &
    (df_model["age"] <= 90) &
    (df_model["time_half_sec"] > 0)
].copy()

print(df_model.shape)

(17909, 7)

In [222]:
df_model[
    ["age", "time_5km_sec", "time_half_sec"]
].describe()

                age  time_5km_sec  time_half_sec
count  17909.000000  17909.000000   17909.000000
mean      39.623430   1672.286951    7391.728684
std       10.256446    246.763119    1211.266579
min       18.000000      0.000000    3843.000000
25%       32.000000   1500.000000    6544.000000
50%       39.000000   1660.000000    7240.000000
75%       46.000000   1833.000000    8127.000000
max       90.000000   3825.000000   12512.000000

In [223]:
df_model["gender_"] = df_model["gender"].map({
    "M": 0,
    "K": 1
})

In [224]:
df_model[["gender", "gender_"]]

      gender  gender_
0          M        0
1          M        0
2          M        0
3          M        0
4          M        0
...      ...      ...
19244      K        1
19245      K        1
19246      K        1
19247      K        1
19248      K        1

[17909 rows x 2 columns]

In [225]:
model_data = df_model[
    [
        "gender",
        "age",
        "time_5km_sec",
        "time_half_sec"
    ]
].copy()

In [226]:
model_data

      gender   age  time_5km_sec  time_half_sec
0          M  32.0         877.0         3899.0
1          M  38.0         888.0         3983.0
2          M  28.0         946.0         4104.0
3          M  36.0         971.0         4216.0
4          M  29.0         972.0         4227.0
...      ...   ...           ...            ...
19244      K  47.0        2396.0        11866.0
19245      K  76.0        2610.0        11987.0
19246      K  46.0        2526.0        12068.0
19247      K  69.0        2960.0        12138.0
19248      K  43.0        2808.0        12512.0

[17909 rows x 4 columns]

In [227]:
from pycaret.regression import *

In [228]:
reg_setup = setup(
    data=model_data,
    target="time_half_sec",
    session_id=42,
    verbose=False
)

In [229]:
best_model = compare_models()

In [230]:
final_model = finalize_model(best_model)

In [231]:
save_model(
    final_model,
    "models/halfmarathon_model"
)

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['age', 'time_5km_sec'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['gender'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('ordinal_encoding',
                  TransformerWrapper(include=['gender'],
                                     transformer=OrdinalEncoder(cols=['gender'],
                                                                handle_missing='return_nan',
                                                                mapping=[{'col': 'gender',
                                                                          'data_type': dtype('O'),
                                                                          'mapping': K      0
 M      1
 NaN   -1
 dtype: int64}]))),
                 ('actual_estimator',
                  GradientBoostingRegressor(random_state=42))]),
 'models/halfmarathon_model.pkl')

In [232]:
import pandas as pd

test_runner = pd.DataFrame({
    "gender": [1],
    "age": [30],
    "time_5km_sec": [1500]
})

predict_model(
    final_model,
    data=test_runner
)

   gender  age  time_5km_sec  prediction_label
0       1   30          1500       6540.204022

In [233]:
from dotenv import load_dotenv
import os

load_dotenv(override=True)

print("ACCESS:", bool(os.getenv("DO_ACCESS_KEY")))
print("SECRET:", bool(os.getenv("DO_SECRET_KEY")))

ACCESS: True
SECRET: True

In [234]:
import boto3
from dotenv import load_dotenv
import os

load_dotenv(override=True)

client = boto3.client(
    "s3",
    endpoint_url=os.getenv("DO_ENDPOINT"),
    aws_access_key_id=os.getenv("DO_ACCESS_KEY"),
    aws_secret_access_key=os.getenv("DO_SECRET_KEY"),
)

response = client.list_objects_v2(
    Bucket=os.getenv("DO_BUCKET_NAME")
)

print(response)

{'ResponseMetadata': {'RequestId': '0BA44223EE4221BC', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'accept-ranges': 'bytes', 'content-length': '1400', 'content-type': 'application/xml', 'x-amz-request-id': '0BA44223EE4221BC', 'date': 'Tue, 09 Jun 2026 14:21:44 GMT'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Contents': [{'Key': 'data/raw/halfmarathon_wroclaw_2023__final.csv', 'LastModified': datetime.datetime(2026, 6, 9, 14, 13, 40, tzinfo=tzutc()), 'ETag': '"9da92a97c9484f41f24df7713a940a6a"', 'Size': 2008515, 'StorageClass': 'STANDARD_IA'}, {'Key': 'data/raw/halfmarathon_wroclaw_2024__final.csv', 'LastModified': datetime.datetime(2026, 6, 9, 14, 13, 41, tzinfo=tzutc()), 'ETag': '"ac9a1d9629277a52fedcb57b53763207"', 'Size': 2651025, 'StorageClass': 'STANDARD_IA'}, {'Key': 'halfmarathon_wroclaw_2023__final.csv', 'LastModified': datetime.datetime(2026, 6, 8, 19, 47, 59, tzinfo=tzutc()), 'ETag': '"9da92a97c9484f41f24df7713a940a6a"', 'Size': 2008515, 'StorageClass': 'STANDARD_IA'}, {'Key': 'halfmarathon_wroclaw_2024__final.csv', 'LastModified': datetime.datetime(2026, 6, 8, 19, 48, tzinfo=tzutc()), 'ETag': '"ac9a1d9629277a52fedcb57b53763207"', 'Size': 2651025, 'StorageClass': 'STANDARD_IA'}, {'Key': 'models/halfmarathon_model.pkl', 'LastModified': datetime.datetime(2026, 6, 9, 14, 13, 42, tzinfo=tzutc()), 'ETag': '"ddcf6f8e2b79863f1810fcb6c3bba08d"', 'Size': 190465, 'StorageClass': 'STANDARD_IA'}], 'Name': 'halfmarathon-ml', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 5, 'ContinuationToken': ''}

In [235]:
client.upload_file(
    "data/raw/halfmarathon_wroclaw_2023__final.csv",
    os.getenv("DO_BUCKET_NAME"),
    "data/raw/halfmarathon_wroclaw_2023__final.csv"
)

print("2023 file upload is finished.")

2023 file upload is finished.

In [236]:
client.upload_file(
    "data/raw/halfmarathon_wroclaw_2024__final.csv",
    os.getenv("DO_BUCKET_NAME"),
    "data/raw/halfmarathon_wroclaw_2024__final.csv"
)

print("2024 file upload is finished.")

2024 file upload is finished.

In [237]:
client.upload_file(
    "models/halfmarathon_model.pkl",
    os.getenv("DO_BUCKET_NAME"),
    "models/halfmarathon_model.pkl"
)

print("Model upload is finished.")

Model upload is finished.

In [238]:
import os

client.download_file(
    os.getenv("DO_BUCKET_NAME"),
    "data/raw/halfmarathon_wroclaw_2023__final.csv",
    "2023.csv"
)

print("Download file is finished.")

Download file is finished.

In [239]:
import pandas as pd

df_test = pd.read_csv(
    "2023.csv",
    sep=";"
)

print(df_test.shape)

(8950, 27)

In [240]:
from openai import OpenAI
from dotenv import load_dotenv
import os
import json

load_dotenv(override=True)

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

user_text = """
Mam 30 lat, jestem kobietą, 5 km biegnę w 25 minut.

"""

response = client.responses.create(

    model="gpt-4o-mini",
    input=f"""

Wyłuskaj dane z tekstu i zwróć tylko i wyłącznie JSON:

{{
  "gender": 0,
  "age": 0,
  "time_5km_sec": 0
}}

Oznaczenie płci: Kobieta 1, Mężczyzna 0
Czas na 5 km zawsze zwróć w sekundach, niezależnie od formatu wejściowego.
Jeśli brakuje danych zwróć null dla danego pola.
Jeśli wiek (age) powyżej 120 lat, to upewnij się o poprawność danych.

Tekst:
{user_text}
"""
)

print(response.output_text)

```json
{
  "gender": 1,
  "age": 30,
  "time_5km_sec": 1500
}
```

In [241]:
import json
import pandas as pd
from pycaret.regression import predict_model

clean_json = (
    response.output_text
    .replace("```json", "")
    .replace("```", "")
    .strip()
)

data = json.loads(clean_json)

test_runner = pd.DataFrame({
    "gender": [data["gender"]],
    "age": [data["age"]],
    "time_5km_sec": [data["time_5km_sec"]]
})

prediction = predict_model(
    final_model,
    data=test_runner
)

prediction[["prediction_label"]]

   prediction_label
0       6540.204022

In [242]:
from pycaret.regression import load_model

final_model = load_model("models/halfmarathon_model")

print(type(final_model))

Transformation Pipeline and Model Successfully Loaded
<class 'pycaret.internal.pipeline.Pipeline'>

In [2]:
print("Notebook działa poprawnie! ✅")

Notebook działa poprawnie! ✅